Bare metal forms and helpers with Rails
KabohaJeanMark/re-former pull request #1
Opened 2021-05-29 09:11 UTC by KabohaJeanMark

- Use the 3 methods of creating forms as they improve functionality.
- Use a better safer implementation with rails' form_tag.
- Use the form_with model helper for an even better implementation that is smarter for a DRY approach.
- Add validations for presence and uniqueness displaying them at the form top.
- Do a full CRUD application providing for updates and deleting of users.
- Refactoring to add partial forms for a DRY approach and cleaner work.
- Proper README documentation with instructions of setting up and use clearly showing the  and how the CRUD operations function.

2021-05-29 12:17 UTC, e71az requested changes
# Status:  Changes Required ♻️

Hello @KabohaJeanMark,

Your project looks good so far, keep up the great job!

I have a small list of things to correct before you can keep moving:

- When I try to create a new user this happens: [screenshot](https://prnt.sc/13ju6wi) please fix it so the next TSE can test the user CRUD correctly, make sure that you can create, read, update and delete users before sending another review request!
- Remove all the commented code that has nothing to do with the one commented at users/new.html.erb view.
- Fix the path at your controller mentioned in the comments.
- Create just the necessary routes for this project.

OPTIONAL:

- Add a correct mail validation with a regex or something else so only real mail formats get accepted.

Please correct those issues and send another review request, good luck, and well done!

2021-05-29 12:17 UTC, eliasecasta commented on config/routes.rb
> +  resources :users
Create only the necessary routes for your app, in this case: new, create, edit, update.

2021-05-29 12:17 UTC, eliasecasta commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password]) # the old way
Remove all the commented code that you may have through the app

2021-05-29 12:17 UTC, eliasecasta commented on test/controllers/users_controller_test.rb
> +  # end
Remove commented code

2021-05-29 12:17 UTC, eliasecasta commented on test/models/user_test.rb
> +  # end
Remove commented code

2021-05-29 12:17 UTC, eliasecasta commented on app/controllers/users_controller.rb
> +      redirect_to @user
Microverse asks us to redirect_to edit_user_path(@user) instead of just @user as you currently have, please fix this.

2021-05-29 12:17 UTC, eliasecasta commented on app/views/users/new.html.erb
> +-->
This commented code is fine, don't delete it.

2021-05-31 08:39 UTC, KabohaJeanMark commented
Thanks 👍🏾  a bunch for the clear and concise feedback @e71az.

I have worked on all the changes plus done the Optional feedback of adding regex to validate the email address on the model level.

It adds a great deal of value to the project 💪🏾

2021-05-31 10:01 UTC, e71az commented
> Thanks 👍🏾 a bunch for the clear and concise feedback @e71az.
> 
> I have worked on all the changes plus done the Optional feedback of adding regex to validate the email address on the model level.
> 
> It adds a great deal of value to the project 💪🏾

I am really happy to know that my review was clear and helpful for you, keep up the good job and that motivation! Good luck in your next projects! :D

2021-05-31 11:59 UTC, oloomoses approved these changes
Hello @KabohaJeanMark,
**Well done on implementing the changes suggested by the @e71az**
### Highlights
- Commented out `form` and `form_tag` :heavy_check_mark:
- Use of form partial :heavy_check_mark:
- Descriptive pr and readme :heavy_check_mark:
- Linters and rubocop configuration :heavy_check_mark:

**This milestone meets all the requirements and therefore:**
## Approved :tada: :muscle: :clap:

**However, there is still room for improvement. Kindly spend a few minutes and work on the below changes before merging.**
### Optional
- [x] It is highly recommended to use `users_path` helper in the `form action`, for the commented out `form` and `form_tag`. The code should be like :point_down: 
```<form action="users_path" method="post" accept-charset="UTF-8">``` and
```<%= form_tag(users_path) do %>```

##### Congratulations once again and best wishes on the next project.

### Happy coding

_Slack: Oloo Moses_

2021-05-31 17:14 UTC, KabohaJeanMark commented
Hello 👋🏾  @oloomoses 
Thanks for pointing out the recommendations for using users_path in the form action for the form and form tag commented out options.
I have optimized the code 💻  by making the changes.

2021-05-31 17:15 UTC, merged

2021-05-31 17:30 UTC, oloomoses commented
> Hello 👋🏾 @oloomoses
> Thanks for pointing out the recommendations for using users_path in the form action for the form and form tag commented out options.
> I have optimized the code  by making the changes.

:muscle: